### ISSUE TITLE
NullPointerException on menu tap under certain circumstances

### ISSUE THREAD

**Issue by gsurrel** [gsurrel/FacebookNotifications#28]
Maybe it's when the page hasn't been fully loaded yet.

```
java.lang.NullPointerException: 
  at android.net.Uri$StringUri.<init>(Uri.java:476)
  at android.net.Uri$StringUri.<init>(Uri.java:466)
  at android.net.Uri.parse(Uri.java:438)
  at org.surrel.facebooknotifications.MainActivity.onOptionsItemSelected(MainActivity.java:222)
  at android.app.Activity.onMenuItemSelected(Activity.java:3205)
  at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1244)
  at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
  at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
  at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
  at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
  at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:658)
  at com.android.internal.view.menu.ActionMenuItemView$1.run(ActionMenuItemView.java:250)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7230)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by gsurrel** [comment]
Probably linked to the `logout` action when the page is not loaded yet. Replace with clearing cookies and cache of the WebView instead.
